### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by amine-boukriba** [him4318/Transformer-ocr#12]
when training the model this error occurred in the first iteration 
```
Epoch: 01 learning rate[0.0001]
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-6360cfd97324> in <module>()
     15     start_time = time.time()
     16 
---> 17     train_loss,outputs = train(model,  criterion, optimizer, scheduler, train_loader)
     18     valid_loss = evaluate(model, criterion, val_loader)
     19 

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py in __iter__(self)
    605         # See gh-54457
    606         if self.dim() == 0:
--> 607             raise TypeError('iteration over a 0-d tensor')
    608         if torch._C._get_tracing_state():
    609             warnings.warn('Iterating over a tensor might cause the trace to be incorrect. '

TypeError: iteration over a 0-d tensor
```

**Comment by him4318** [comment]
The issue is maybe with your data.

**Comment by him4318** [comment]
![image](https://user-images.githubusercontent.com/31626936/133373283-cf7d1d3f-2458-48af-bbd8-26fde44fcfe5.png)

For me, it's working fine. I have also updated the requirement.txt file. Can you check now?

**Comment by him4318** [comment]
![133373283-cf7d1d3f-2458-48af-bbd8-26fde44fcfe5](https://user-images.githubusercontent.com/31626936/133375835-1e72697d-8490-4c0c-9d60-f81dc1773ae2.png)
It is working fine for me. I have also updated the requirement.txt, can you check now?

**Comment by amine-boukriba** [comment]
same thing I even checked if the data loaders are empty and they are not




<br>
<img width="294" alt="2021-09-25 (13)" src="https://user-images.githubusercontent.com/43059827/134774879-7c00dc1f-3b0a-4f5c-b126-1867fd32b293.png">

**Comment by Nivratti** [comment]
Replace train function call 

`train_loss,outputs = train(model,  criterion, optimizer, scheduler, train_loader)`

with 

`train_loss = train(model,  criterion, optimizer, scheduler, train_loader)`

As train function returns only single value, not typle.

**Comment by him4318** [comment]
I checked it is correct in the Google colab but this error exists in Notebook. I'll change it.
Thanks for pointing out.
